apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-plaintext-secrets
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-env-secrets
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Les mots de passe en clair dans les variables d'environnement sont interdits"
      pattern:
        spec:
          containers:
          - env:
            - name: "!*PASSWORD*"
              value: "null"
            - name: "!*SECRET*"
              value: "null"
            - name: "!*TOKEN*"
              value: "null"
            - name: "!*KEY*"
              value: "null"
